spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-update
  profiles.active: prod

---
spring:
  profiles: dev

  datasource:
    url: jdbc:h2:mem:aloogue;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect

h2:
  path: /h2/*
  console-enabled: true

---

spring:
  profiles: prod
---